lab/urls.py
from django.urls import path
from .views import LabCreateView
from . import views

app_name = 'lab'

urlpatterns = [
    path('create/', LabCreateView.as_view(), name='create'),
    path('labcreate/', views.labcreate, name='labcreate'),
]

myproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('account/', include('account.urls')),
    # path('annoucement/', include('annoucement.urls')),
    path('', include('notice.urls')),
    path('', include('lab.urls')),
    path('', include('notice2.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab/models.py
from django.db import models

from account.models import User


class Lab(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name='lab', null=True)

    title = models.CharField(max_length=200, null=True)
    
    # image = models.ImageField(upload_to='image/', null=True)
    # file = models.FileField(upload_to='lab/', null=True)
    # image = models.ImageField(null=True)
    file = models.FileField(null=True)
    
    content = models.TextField(null=True)

    createdAt = models.DateField(auto_now_add=True, null=True)

    class Meta:
        db_table = 'lab'

lab/forms.py
from django import forms
from django.forms import ClearableFileInput
from lab.models import Lab


class LabCreationForm(forms.ModelForm):

    # image = forms.ImageField(required=False)
    file = forms.FileField(required=False)

    class Meta:
        model = Lab
        # fields = ['title', 'content', 'image', 'file']
        fields = ['title', 'content', 'file']
        # widgets = {
        #     'file': ClearableFileInput(attrs={'multiple': True})
        # }

lab/views.py
from django.http import HttpRequest, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import CreateView
from account.models import User
from base.views import getSessionUserId, responseAjax

from lab.forms import LabCreationForm
from lab.models import Lab

from django.core.files.storage import FileSystemStorage


def labcreate(request: HttpRequest):
    if request.method == 'POST':
        try:
            form = LabCreationForm(request.POST, request.FILES)
            # print(form)
            # print(type(form))
            # <class 'lab.forms.LabCreationForm'>

            if form.is_valid():
                # print(form.cleaned_data['author'])
                # User object (1)

                # print(type(form.cleaned_data['author']))
                # <class 'account.models.User'>

                # print(User.objects.filter(pk=request.session.get('user')['id']).first())
                # User object (1)

                # print(type(User.objects.filter(
                #     pk=request.session.get('user')['id']).first()))

                # form.cleaned_data['author'] = User.objects.filter(
                #     pk=request.session.get('user')['id']).first()
                # 변경 불가 속성

                temp_lab: Lab = form.save(commit=False)
                temp_lab.author = User.objects.filter(pk=getSessionUserId(request)).first()

                # print(temp_lab)
                # Lab object (None)

                # print(type(temp_lab))
                # <class 'lab.models.Lab'>

                files = request.FILES.getlist('file')
                fileList = []

                # print(files)
                # [<TemporaryUploadedFile: 파일명.파일확장자 (application/x-msdownload)>]

                # print(type(files))
                # <class 'list'>

                for tempFile in files:
                    fs = FileSystemStorage(base_url="lab/")
                    
                    print(f"1 : {tempFile}")
                    # 파일명.파일확장자
                    # print(type(tempFile))
                    # <class 'django.core.files.uploadedfile.TemporaryUploadedFile'>
                    
                    print(f"2 : {tempFile.name}")
                    
                    tempFilePath = fs.save(f"lab/{tempFile.name}", tempFile)
                    print(f"3: {tempFilePath}")
                    # 경로/파일명.파일확장자
                    
                    fileList.append(tempFilePath)
                    
                    
                temp_lab.file = str(fileList)

                # form.save()
                temp_lab.save()

                return JsonResponse(responseAjax("등록 성공", 1))
            else:
                # print(form.errors)
                return JsonResponse(responseAjax("등록 실패", 0, form.errors))
        except Exception as e:
            print(e)
            return JsonResponse(responseAjax("에러 발생", -1,))
    else:
        if getSessionUserId(request) == None:
            return redirect('/account/login')

        form = LabCreationForm()
        return render(request, 'labcreate.html', {'form': form})


class LabCreateView(CreateView):
    model = Lab

    form_class = LabCreationForm

    template_name = 'lab/templates/create.html'

    def form_valid(self, form):
        temp_lab: Lab = form.save(commit=False)

        request = HttpRequest

        temp_lab.author = User.objects.filter(pk=getSessionUserId(request)).first()
        temp_lab.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('')

lab/templates/create.html
{% extends 'base.html' %}
<!-- -->
{% block content %}
<!-- -->

<div>
  <h1>Lab Create</h1>
  <form action="{% url 'lab:create' %}" method="post">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="submit" />
  </form>
</div>

<!-- -->
{% endblock %}

lab/templates/labcreate.html
{% extends 'base.html' %}
<!-- -->
{% load static %}
<!--  -->
{% block content %}
<!-- -->
<div>
  <h1>Lab Create</h1>
  <form enctype="multipart/form-data" id="form" method="POST">
    {%csrf_token%} {% comment %}{{form.as_p}} {% endcomment %}
    <div>
      <span>제목</span>
      <input type="text" name="title" maxlength="200" required id="id_title" />
    </div>

    <div>
      <span>내용</span>
      <textarea name="content" cols="40" rows="10" required id="id_content"></textarea>
    </div>

    <div>
      <span>이미지</span>
      <input type="file" name="image" accept="image/*" id="id_image" />
    </div>

    <div>
      <span>파일</span>
      <!-- <input type="file" name="file" id="id_file" /> -->
      <input type="file" name="file" />
      <input type="file" name="file" />
    </div>

    <input type="submit" />
    <div class="form-group" style="display: none" id="progress_div">
      <br />
      <div class="progress">
        <div
          class="progress-bar"
          id="progress_bar"
          role="progressbar"
          style="width: 0%"
          aria-valuenow="0"
          aria-valuemin="0"
          aria-valuemax="100"
        >
          0%
        </div>
      </div>
    </div>
    <div class="row form-group">
      <p id="progress_text"></p>
    </div>
  </form>
</div>
<script src="{% static '/js/lab.js' %}"></script>
<!-- -->
{% endblock %}